In [ ]:
#Görev 1: Seaborn kütüphanesi içerisinden Titanic veri setini tanımlayınız.
import seaborn as sns
import pandas as pd
import numpy as np
df = sns.load_dataset("titanic")
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [ ]:
#Görev 2: Titanic veri setindeki kadın ve erkek yolcuların sayısını bulunuz.
df_gender = df.groupby("sex").size()
print(df_gender)

sex
female    314
male      577
dtype: int64

In [ ]:
#Görev 3: Her bir sutuna ait unique değerlerin sayısını bulunuz.

df.nunique()

survived         2
pclass           3
sex              2
age             88
sibsp            7
parch            7
fare           248
embarked         3
class            3
who              3
adult_male       2
deck             7
embark_town      3
alive            2
alone            2
dtype: int64

In [ ]:
#Görev 4: pclass değişkeninin unique değerlerinin sayısını bulunuz.

df["pclass"].unique()

array([3, 1, 2])

In [ ]:
#Görev 5: pclass ve parch değişkenlerinin unique değerlerinin sayısını bulunuz.

df[["pclass","parch"]].nunique()

pclass    3
parch     7
dtype: int64

In [ ]:
#Görev 6: embarked değişkeninin tipini kontrol ediniz. Tipini category olarak değiştiriniz ve tekrar kontrol ediniz.
df["embarked"].dtype #dtype = object
df["embarked"] = df["embarked"].astype("category")
df["embarked"].dtype #dtype = categorical

CategoricalDtype(categories=['C', 'Q', 'S'], ordered=False)

In [ ]:
#Görev 7: embarked değeri C olanların tüm bilgelerini gösteriniz.

df[df["embarked"] == "C"]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
9,1,2,female,14.0,1,0,30.0708,C,Second,child,False,NaN,Cherbourg,yes,False
19,1,3,female,NaN,0,0,7.2250,C,Third,woman,False,NaN,Cherbourg,yes,True
26,0,3,male,NaN,0,0,7.2250,C,Third,man,True,NaN,Cherbourg,no,True
30,0,1,male,40.0,0,0,27.7208,C,First,man,True,NaN,Cherbourg,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
866,1,2,female,27.0,1,0,13.8583,C,Second,woman,False,NaN,Cherbourg,yes,False
874,1,2,female,28.0,1,0,24.0000,C,Second,woman,False,NaN,Cherbourg,yes,False
875,1,3,female,15.0,0,0,7.2250,C,Third,child,False,NaN,Cherbourg,yes,True
879,1,1,female,56.0,0,1,83.1583,C,First,woman,False,C,Cherbourg,yes,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True

In [ ]:
#Görev 8: embarked değeri S olmayanların tüm bilgelerini gösteriniz.

df[df["embarked"] != "S"]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
5,0,3,male,NaN,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True
9,1,2,female,14.0,1,0,30.0708,C,Second,child,False,NaN,Cherbourg,yes,False
16,0,3,male,2.0,4,1,29.1250,Q,Third,child,False,NaN,Queenstown,no,False
19,1,3,female,NaN,0,0,7.2250,C,Third,woman,False,NaN,Cherbourg,yes,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
875,1,3,female,15.0,0,0,7.2250,C,Third,child,False,NaN,Cherbourg,yes,True
879,1,1,female,56.0,0,1,83.1583,C,First,woman,False,C,Cherbourg,yes,False
885,0,3,female,39.0,0,5,29.1250,Q,Third,woman,False,NaN,Queenstown,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [ ]:
#Görev9: Yaşı 30'dan küçük ve kadın olany olcuların tüm bilgilerini gösteriniz.

df[(df["age"] < 30) & (df["sex"] == "female")].head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
8,1,3,female,27.0,0,2,11.1333,S,Third,woman,False,NaN,Southampton,yes,False
9,1,2,female,14.0,1,0,30.0708,C,Second,child,False,NaN,Cherbourg,yes,False
10,1,3,female,4.0,1,1,16.7000,S,Third,child,False,G,Southampton,yes,False
14,0,3,female,14.0,0,0,7.8542,S,Third,child,False,NaN,Southampton,no,True

In [ ]:
#Görev 10: Fare'i 500'den büyük veya yaşı 70 den büyük yolcuların bilgilerini gösteriniz.

df[(df["fare"] > 500) | (df["age"] > 70)].head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
96,0,1,male,71.0,0,0,34.6542,C,First,man,True,A,Cherbourg,no,True
116,0,3,male,70.5,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True
258,1,1,female,35.0,0,0,512.3292,C,First,woman,False,NaN,Cherbourg,yes,True
493,0,1,male,71.0,0,0,49.5042,C,First,man,True,NaN,Cherbourg,no,True
630,1,1,male,80.0,0,0,30.0000,S,First,man,True,A,Southampton,yes,True

In [ ]:
#Görev 11: Her bir değişkendeki boş değerlerin toplamını bulunuz.
df.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [ ]:
#Görev 12: who değişkenini dataframe’den çıkarınız.

df.drop("who", axis=1, inplace=True)

df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,True,NaN,Queenstown,no,True

In [ ]:
#Görev 13: deck değişkenindeki boş değerleri deck değişkenin en çok tekrar eden değeri (mode) ile doldurunuz.
#SOR
df["deck"] = df["deck"].fillna(df["deck"].mode()[0])
df["deck"]
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,C,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,C,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,C,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,C,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,C,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,C,Queenstown,no,True

In [ ]:
#Görev 14: age değikenindeki boş değerleri age değişkenin medyanı ile doldurunuz.

df["age"].fillna(df["age"].median())
df["age"]

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: age, Length: 891, dtype: float64

In [ ]:
#Görev 15: survived değişkeninin pclass ve cinsiyet değişkenleri kırılımınında sum, count, mean değerlerini bulunuz.

df.groupby(["pclass", "sex"]).agg({"survived": ["sum", "count", "mean"]}).head()

              survived
                   sum count      mean
pclass sex
1      female       91    94  0.968085
       male         45   122  0.368852
2      female       70    76  0.921053
       male         17   108  0.157407
3      female       72   144  0.500000

In [ ]:
'''Görev 16: 30 yaşın altında olanlar 1, 30'a eşit ve üstünde olanlara 0 vericek bir fonksiyon yazın.
#Yazdığınız fonksiyonu kullanarak titanik veri setinde age_flag adında bir değişken oluşturunuz.
(apply ve lambda yapılarını kullanınız)'''

df["age_flag"] = df["age"].apply(lambda x: 1 if x < 30 else 0)
df["age_flag"].head()

0    1
1    0
2    1
3    0
4    0
Name: age_flag, dtype: int64

In [ ]:
#Görev 17: Seaborn kütüphanesi içerisinden Tips veri setini tanımlayınız.
df = sns.load_dataset("tips")
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [ ]:
'''Görev 18: Time değişkeninin kategorilerine (Dinner, Lunch) göre
total_bill değerlerinin toplamını, min, max ve ortalamasını bulunuz.'''

df.groupby("time").agg({"total_bill": ["sum", "min", "max", "mean"]})

       total_bill
              sum   min    max       mean
time
Lunch     1167.47  7.51  43.11  17.168676
Dinner    3660.30  3.07  50.81  20.797159

In [ ]:
#Görev 19: Günlere ve time göre total_bill değerlerinin toplamını, min, max ve ortalamasını bulunuz.
df.groupby(["day","time"]).agg({"total_bill": ["sum","min","max","mean"]})

            total_bill
                   sum    min    max       mean
day  time
Thur Lunch     1077.55   7.51  43.11  17.664754
     Dinner      18.78  18.78  18.78  18.780000
Fri  Lunch       89.92   8.58  16.27  12.845714
     Dinner     235.96   5.75  40.17  19.663333
Sat  Lunch        0.00    NaN    NaN        NaN
     Dinner    1778.40   3.07  50.81  20.441379
Sun  Lunch        0.00    NaN    NaN        NaN
     Dinner    1627.16   7.25  48.17  21.410000

In [ ]:
'''Görev 20: Lunch zamanına ve kadın müşterilere ait total_bill ve tip değerlerinin
day'e göre toplamını, min, max ve ortalamasını bulunuz.'''



df.loc[(df["time"]== "Lunch") & (df["sex"]=="Female")] #Lunch, ve kadın

     total_bill   tip     sex smoker   day   time  size
82        10.07  1.83  Female     No  Thur  Lunch     1
85        34.83  5.17  Female     No  Thur  Lunch     4
117       10.65  1.50  Female     No  Thur  Lunch     2
118       12.43  1.80  Female     No  Thur  Lunch     2
119       24.08  2.92  Female     No  Thur  Lunch     4
121       13.42  1.68  Female     No  Thur  Lunch     2
124       12.48  2.52  Female     No  Thur  Lunch     2
125       29.80  4.20  Female     No  Thur  Lunch     6
127       14.52  2.00  Female     No  Thur  Lunch     2
128       11.38  2.00  Female     No  Thur  Lunch     2
131       20.27  2.83  Female     No  Thur  Lunch     2
132       11.17  1.50  Female     No  Thur  Lunch     2
133       12.26  2.00  Female     No  Thur  Lunch     2
134       18.26  3.25  Female     No  Thur  Lunch     2
135        8.51  1.25  Female     No  Thur  Lunch     2
136       10.33  2.00  Female     No  Thur  Lunch     2
137       14.15  2.00  Female     No  Thur  Lunch     2
139       13.16  2.75  Female     No  Thur  Lunch     2
140       17.47  3.50  Female     No  Thur  Lunch     2
143       27.05  5.00  Female     No  Thur  Lunch     6
144       16.43  2.30  Female     No  Thur  Lunch     2
145        8.35  1.50  Female     No  Thur  Lunch     2
146       18.64  1.36  Female     No  Thur  Lunch     3
147       11.87  1.63  Female     No  Thur  Lunch     2
191       19.81  4.19  Female    Yes  Thur  Lunch     2
197       43.11  5.00  Female    Yes  Thur  Lunch     4
198       13.00  2.00  Female    Yes  Thur  Lunch     2
201       12.74  2.01  Female    Yes  Thur  Lunch     2
202       13.00  2.00  Female    Yes  Thur  Lunch     2
203       16.40  2.50  Female    Yes  Thur  Lunch     2
205       16.47  3.23  Female    Yes  Thur  Lunch     3
221       13.42  3.48  Female    Yes   Fri  Lunch     2
223       15.98  3.00  Female     No   Fri  Lunch     3
225       16.27  2.50  Female    Yes   Fri  Lunch     2
226       10.09  2.00  Female    Yes   Fri  Lunch     2

In [ ]:
df.groupby(["day"]).agg({"total_bill" :["sum","min","max"],
                        "tip":["sum","min","max"]}) #sum, min, max'lar vb. listelenir.

     total_bill                  tip
            sum   min    max     sum   min    max
day
Thur    1096.33  7.51  43.11  171.83  1.25   6.70
Fri      325.88  5.75  40.17   51.96  1.00   4.73
Sat     1778.40  3.07  50.81  260.40  1.00  10.00
Sun     1627.16  7.25  48.17  247.39  1.01   6.50

In [ ]:
df.loc[(df["time"]== "Lunch") & (df["sex"]=="Female")].groupby(["day"]).agg({"total_bill" :["sum","min","max"],"tip":["sum","min","max"]})  #Son hali.

     total_bill                  tip
            sum    min    max    sum   min   max
day
Thur     516.11   8.35  43.11  79.42  1.25  5.17
Fri       55.76  10.09  16.27  10.98  2.00  3.48
Sat        0.00    NaN    NaN   0.00   NaN   NaN
Sun        0.00    NaN    NaN   0.00   NaN   NaN

In [ ]:
#Görev 21: size'i 3'ten küçük, total_bill'i 10'dan büyük olan siparişlerin ortalaması nedir? (loc kullanınız)
df.loc[(df["size"] < 3) & (df["total_bill"] > 10)].mean(numeric_only=True)

total_bill    17.184965
tip            2.638811
size           1.993007
dtype: float64

In [ ]:
#Görev 22: total_bill_tip_sum adında yeni bir değişken oluşturunuz. Her bir müşterinin ödediği totalbill ve tip in toplamını versin.

df["total_bill_tip_sum"] = df["total_bill"] + df["tip"]
df.head()

   total_bill   tip     sex smoker  day    time  size  total_bill_tip_sum
0       16.99  1.01  Female     No  Sun  Dinner     2               18.00
1       10.34  1.66    Male     No  Sun  Dinner     3               12.00
2       21.01  3.50    Male     No  Sun  Dinner     3               24.51
3       23.68  3.31    Male     No  Sun  Dinner     2               26.99
4       24.59  3.61  Female     No  Sun  Dinner     4               28.20

In [ ]:
#Görev 23: total_bill_tip_sum değişkenine göre büyükten küçüğe sıralayınız ve ilk 30 kişiyi yeni bir dataframe'e atayınız.

df = df.sort_values("total_bill_tip_sum", ascending=False).head(30)
df

     total_bill    tip     sex smoker   day    time  size  total_bill_tip_sum
170       50.81  10.00    Male    Yes   Sat  Dinner     3               60.81
212       48.33   9.00    Male     No   Sat  Dinner     4               57.33
59        48.27   6.73    Male     No   Sat  Dinner     4               55.00
156       48.17   5.00    Male     No   Sun  Dinner     6               53.17
182       45.35   3.50    Male    Yes   Sun  Dinner     3               48.85
197       43.11   5.00  Female    Yes  Thur   Lunch     4               48.11
23        39.42   7.58    Male     No   Sat  Dinner     4               47.00
102       44.30   2.50  Female    Yes   Sat  Dinner     3               46.80
142       41.19   5.00    Male     No  Thur   Lunch     5               46.19
95        40.17   4.73    Male    Yes   Fri  Dinner     4               44.90
184       40.55   3.00    Male    Yes   Sun  Dinner     2               43.55
112       38.07   4.00    Male     No   Sun  Dinner     3               42.07
207       38.73   3.00    Male    Yes   Sat  Dinner     4               41.73
56        38.01   3.00    Male    Yes   Sat  Dinner     4               41.01
141       34.30   6.70    Male     No  Thur   Lunch     6               41.00
238       35.83   4.67  Female     No   Sat  Dinner     3               40.50
11        35.26   5.00  Female     No   Sun  Dinner     4               40.26
52        34.81   5.20  Female     No   Sun  Dinner     4               40.01
85        34.83   5.17  Female     No  Thur   Lunch     4               40.00
47        32.40   6.00    Male     No   Sun  Dinner     4               38.40
180       34.65   3.68    Male    Yes   Sun  Dinner     4               38.33
179       34.63   3.55    Male    Yes   Sun  Dinner     2               38.18
83        32.68   5.00    Male    Yes  Thur   Lunch     2               37.68
39        31.27   5.00    Male     No   Sat  Dinner     3               36.27
167       31.71   4.50    Male     No   Sun  Dinner     4               36.21
175       32.90   3.11    Male    Yes   Sun  Dinner     2               36.01
44        30.40   5.60    Male     No   Sun  Dinner     4               36.00
173       31.85   3.18    Male    Yes   Sun  Dinner     2               35.03
116       29.93   5.07    Male     No   Sun  Dinner     4               35.00
155       29.85   5.14  Female     No   Sun  Dinner     5               34.99